import { FormEvent, useState } from "react";
import { Bot, Loader2, Send } from "lucide-react";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { askCareerAssistant } from "../../lib/ai-api";

type Message = {
  role: "user" | "assistant";
  text: string;
  actions?: string[];
};

export function CareerAssistantPage() {
  const [message, setMessage] = useState("How should I prepare for a full-stack internship in 8 weeks?");
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      text: "Ask about skills, projects, interview preparation, resume positioning, or learning paths.",
      actions: ["Try a target role question", "Ask for a project idea", "Ask how to improve your resume"],
    },
  ]);
  const [isLoading, setIsLoading] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const trimmed = message.trim();
    if (!trimmed) {
      return;
    }
    setMessages((current) => [...current, { role: "user", text: trimmed }]);
    setMessage("");
    setIsLoading(true);
    try {
      const response = await askCareerAssistant(trimmed);
      setMessages((current) => [...current, { role: "assistant", text: response.answer, actions: response.suggestedActions }]);
    } catch {
      setMessages((current) => [
        ...current,
        {
          role: "assistant",
          text: "I could not reach the backend right now. Once it is running, I can generate personalized career guidance from your Skillora profile.",
          actions: ["Check Spring Boot", "Check the FastAPI service", "Try again"],
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <Badge variant="success">AI Career Assistant</Badge>
        <h1 className="mt-3 text-3xl font-black text-ink-950 dark:text-white sm:text-4xl">
          Career coaching chat
        </h1>
        <p className="mt-2 max-w-2xl text-sm leading-6 text-ink-600 dark:text-ink-300">
          Ask about skills, projects, interview preparation, and learning paths using your Skillora profile context.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Assistant thread</CardTitle>
          <CardDescription>Responses are generated by FastAPI AI service or backend fallback logic.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="max-h-[58vh] space-y-4 overflow-y-auto pr-1">
            {messages.map((item, index) => (
              <div className={item.role === "user" ? "flex justify-end" : "flex justify-start"} key={`${item.role}-${index}`}>
                <div className={item.role === "user" ? "max-w-3xl rounded-lg bg-ink-950 p-4 text-white dark:bg-white dark:text-ink-950" : "max-w-3xl rounded-lg bg-ink-50 p-4 dark:bg-white/[0.045]"}>
                  {item.role === "assistant" ? (
                    <div className="mb-2 flex items-center gap-2 text-sm font-bold text-teal-700 dark:text-teal-200">
                      <Bot aria-hidden="true" className="h-4 w-4" />
                      Skillora
                    </div>
                  ) : null}
                  <p className="text-sm leading-6">{item.text}</p>
                  {item.actions?.length ? (
                    <div className="mt-4 flex flex-wrap gap-2">
                      {item.actions.map((action) => (
                        <Badge key={action} variant="outline">{action}</Badge>
                      ))}
                    </div>
                  ) : null}
                </div>
              </div>
            ))}
          </div>

          <form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={handleSubmit}>
            <textarea
              className="min-h-12 flex-1 rounded-lg border border-ink-200 bg-white px-3 py-3 text-sm text-ink-900 outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20 dark:border-white/10 dark:bg-white/10 dark:text-white"
              onChange={(event) => setMessage(event.target.value)}
              placeholder="Ask Skillora about your career plan..."
              value={message}
            />
            <Button className="sm:w-36" disabled={isLoading} type="submit">
              {isLoading ? <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" /> : <Send aria-hidden="true" className="h-4 w-4" />}
              Send
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
